/**
 * @file showcase.ts
 * @description Static showcase project data for oh-my-copilot.
 * Featured items (featured: true) render as large cards on the Showcase page and
 * the homepage preview. Non-featured items render as compact grid tiles.
 * Update this file to add real projects as they ship.
 */

import type { ShowcaseItem } from "@/types/showcase";

/** All showcase projects — featured first, then compact. */
export const SHOWCASE_ITEMS: readonly ShowcaseItem[] = [
  // ── Featured / Large (3) ─────────────────────────────────────────────────
  {
    id: "teamflow",
    name: "TeamFlow",
    description:
      "A team task management SaaS with real-time collaboration, sprint planning, and AI-powered workload balancing. Built end-to-end in a single weekend using oh-my-copilot agents.",
    tags: ["Next.js", "Go", "PostgreSQL", "Tailwind", "WebSocket"],
    status: "Coming Soon",
    link: "#",
    featured: true,
  },
  {
    id: "storefront",
    name: "StoreFront",
    description:
      "Full-stack e-commerce platform with inventory management, Stripe checkout, and an admin dashboard — all generated by Boss + Worker in a structured multi-sprint workflow.",
    tags: ["Next.js", "Go", "Stripe", "Tailwind", "Redis"],
    status: "Coming Soon",
    link: "#",
    featured: true,
  },
  {
    id: "devnest",
    name: "DevNest",
    description:
      "A developer-focused code snippet manager with syntax highlighting, smart tagging, and team sharing. Your personal GitHub Gists, but purpose-built and self-hosted.",
    tags: ["Next.js", "Go", "PostgreSQL", "shadcn/ui"],
    status: "Coming Soon",
    link: "#",
    featured: true,
  },

  // ── Compact / Small (6) ──────────────────────────────────────────────────
  {
    id: "cashlens",
    name: "CashLens",
    description:
      "Personal finance tracker with visual spending breakdowns and monthly goals.",
    tags: ["Next.js", "Tailwind"],
    status: "Coming Soon",
    link: "#",
    featured: false,
  },
  {
    id: "quickmark",
    name: "QuickMark",
    description:
      "Browser bookmark manager with full-text search and tag organisation.",
    tags: ["Next.js", "Go"],
    status: "Coming Soon",
    link: "#",
    featured: false,
  },
  {
    id: "jobboard",
    name: "JobBoard",
    description: "Niche job board with applicant tracking and one-click apply.",
    tags: ["Next.js", "Go", "PostgreSQL"],
    status: "Coming Soon",
    link: "#",
    featured: false,
  },
  {
    id: "recipebox",
    name: "RecipeBox",
    description:
      "Recipe collection with meal planning and auto-generated shopping lists.",
    tags: ["Next.js", "Tailwind"],
    status: "Coming Soon",
    link: "#",
    featured: false,
  },
  {
    id: "focusring",
    name: "FocusRing",
    description:
      "Pomodoro timer with focus session analytics and daily streak tracking.",
    tags: ["Next.js", "shadcn/ui"],
    status: "Coming Soon",
    link: "#",
    featured: false,
  },
  {
    id: "freelancecrm",
    name: "FreelanceCRM",
    description: "Lightweight CRM built for freelancers and solo consultants.",
    tags: ["Next.js", "Go", "Tailwind"],
    status: "Coming Soon",
    link: "#",
    featured: false,
  },
];

/** Featured showcase items (large cards). */
export const FEATURED_SHOWCASE: readonly ShowcaseItem[] = SHOWCASE_ITEMS.filter(
  (item) => item.featured,
);

/** Non-featured showcase items (compact grid tiles). */
export const COMPACT_SHOWCASE: readonly ShowcaseItem[] = SHOWCASE_ITEMS.filter(
  (item) => !item.featured,
);
